export interface GoodSale {  
    goodSaleId: number,
    inventoryId: number,
    supplierId: number,
    paymentStatusId: number,
    bankInfoId: number,
    saleQty: number,
    salePrice: number,
    saleDueAmount: number,
    saleLessAmount: number,
    totalSalePrice: number,
    salePaidAmount: number,
    saleDuePaidAmount: number,
    weightingScaleNo: number,
    tolyRent:number,
    voucherNo: string,
    chequeNo: string,
    saleDate: string,
    remarks: string,
    approveStatus: number,
    isActive: true,
    inventory: string,
    supplier: string,
    paymentStatus: string,
    bankInfo: string
}
