export interface Inventory {    
    inventoryId: number,
    warehouseId: number,
    requisitionId:number,
    productionId:number,
    supplierId: number,
    inventoryType: number,
    productTypeId: number,
    categoryId: number,
    bankInfoId: number,
    paymentStatusId: number,
    purchaseQty: number,
    availableQty:number,
    productionQty:number,
    sellQty:number,
    damageQty:number,
    totalBags:number,
    weightingScaleNo:number,
    purchaseDate: string,
    voucherNo: string,
    moneyReceived:string,
    returnQty:number,
    purchasePrice:number,
    lessAmount: number,
    totalPurchasePrice: number,
    paidAmount:number,
    dueAmount:number,
    duePaidAmount:number,
    chequeNo: string,
    remarks: string,
    otherStatus:number,
    approveStatus:number,
    category:string,
    isActive: boolean,
    tolyRent:number,
    supplierName:string,
    productType:string,
    warehouseName:string
}
