export interface ShopInventory {    
    shopInventoryId: number,
    warehouseId: number,
    supplierId:number,
    paymentStatusId:number,
    voucherNo: string,
    purchaseDate: string,
    subTotalPrice:string;
    lessAmount: string,
    transportCost: string,
    totalPurchasePrice: string,
    paidAmount: string,
    dueAmount: number,
    approveStatus:boolean,
    shopInventoryDetailId:number,
    fisheriesProductTypeId:number,
    fisheriesUnitId:number,
    productName:string,
    costingPrice: string,
    totalUnitQty: string,
    unitPurchasePrice:string,
    totalUnitPurchasePrice:string,
    availableQty:string,
    damageQty: string,
    returnQty: string,
    isActive: boolean
}
