using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchoolManagement.Application.Enum
{
    public static class DeclareFeatureCode
    {
        public const int FEATURE = 1;
        public const int MODULE = 2;
        public const int ROLE = 3;
        public const int USER = 4;
        public const int DASHBOARD = 5;
        public const int PASSWORDCHANGE = 6;
        public const int EASYBIKETYPE = 7;
        public const int EASYBIKEBANK = 8;
        public const int WAREHOUSE = 9;
        public const int PRODUCTTYPE = 10;
        public const int SUPPLIER = 11;
        public const int PAYMENTSTATUS = 12;
        public const int BANKTRANSACTION = 13;
        public const int CASHINHAND = 14;
        public const int CASHDABIT = 15;
        public const int INVENTORY = 16;
        public const int ADVANCEPAYMENT = 17;
        public const int BANKTRANSACTIONTYPE = 18;
        public const int INVENTORYSALE = 19;
        public const int INVENTORYDUEPAID = 20;
        public const int PAYABLEPAID = 21;
        public const int GOODSALE = 22;
        public const int EMPOLYEE = 23;
        public const int SALARY = 24;
        public const int DAILYCOST = 25;
        public const int BUYPRODUCT = 26;
        public const int MAKENEWPRODUCT = 27;
        public const int SALERETURN = 28;
        public const int Division = 29;
        public const int DISTRICT = 30;
        public const int UPOZILA = 31;
        public const int PRODUCTIONLOG = 32;
        public const int CUSTOMERTYPE = 33;
        public const int SUPPLIERTYPE = 34;
        public const int PRODUCTPIN = 35;
        public const int PRODUCTMETER = 36;
        public const int UNITOFMEASUREMENT = 37;
        public const int ITEMPRODUCTIONTYPE = 38;
        public const int PRODUCTSERIES = 39;
        public const int PRODUCTMODEL = 40;
        public const int BRAND = 41;
        public const int SALEREPRESENTATIVE = 42;
        public const int TRANSFER = 43;
        public const int PRODUCTIONPARAMETER = 44;
        public const int DESIGNATION = 45;
        public const int RRQUISITION = 46;
        public const int TRANSFERRECIVE = 47;
        public const int COUNTRY = 48;
        public const int ACCOUNTNAME = 49;
        public const int ACCOUNTTYPE = 50;
        public const int PRODUCTION = 51;
        public const int DAMAGE = 52;
        public const int SUBCATEGORY = 53;
        public const int DEALERREQUISITION = 54;
        public const int REQUISITIONITEMDELIVERY = 55;
        public const int DEALERPRODUCTTYPE = 56;
        public const int DEALERSTOCK = 57;
        public const int SALARYGRADE = 58;
        public const int SALARYVOLUME = 59;
        public const int RELIGION = 60;
        public const int BLOODGROUP = 61;
        public const int MARITALSTATUS = 62;
        public const int SERVICESTATUS = 63;
        public const int GPAVOLUME = 64;
        public const int GENDER = 65;
        public const int EMPLOYEERELATIONTYPE = 66;
        public const int EMPLOYEERELATIVEINFORMATION = 67;
        public const int EMPLOYEEEDUCATION = 68;
        public const int EMPLOYEETRAINING = 69;
        public const int EMPLOYEEADDRESS = 70;
        public const int EMPLOYEELEAVE = 71;
        public const int EMPATTENDANCE = 72;
        public const int DEALERSALE = 73;
        public const int SRREQUISITION = 74;
        public const int SALARYGRADEPAYSCALE = 75;
        public const int SALARYHEAD = 76;
        public const int SALARYSTRUCTURE = 77;
        public const int SALARYPROCES = 78;
        public const int GPFACCOUNT = 79;
        public const int BANK = 80;
        public const int LEAVETYPE = 81;
        public const int DEPARTMENTPOSTPOSITION = 82;
        public const int LONETYPE = 83;
        public const int EMPLOYEEGPFLOAN = 84;
        public const int EMPINCREMENT = 85;
        public const int EMPOLYEEPROMOTION = 86;
        public const int EMPOLYEETRANSFER = 87;
        public const int GPFINTARESTCALCULATION = 88;
        public const int FISCALYEAR = 89;
        public const int SUPPORTINGUNIVERSITY = 90;
        public const int BUDGETHEADNAME = 91;
        public const int BUDGETFUND = 92;
        public const int BUDGETFUNDTRANSECTION = 93;
        public const int ACCOUNTHEAD = 94;
        public const int BUDGETSUBHEADNAME = 95;
        public const int GLACCOUNTTRANSECTION = 96;
        public const int ACCOUNTSUBHEAD = 97;
        public const int NODELEVEL = 98;
        public const int ACCOUNTNODE = 99;
        public const int GLACCOUNT = 100;
        public const int APPROVALSETUP = 101;
        public const int WAREHOUSESUBDEPARTMENT = 102;
        public const int ASSETCATEGORY = 103;
        public const int ASSETREGISTRATION = 104;
        public const int ASSETISSUE = 105;
        public const int ASSETNAME = 106;
        public const int EMPLOYEEMOVEMENT = 107;
        public const int ESHOPORDER = 108;
        public const int AWARDANDEVENT = 109;
        public const int TVCVIDEO = 110;
        public const int MANAGEMENT = 111;
        public const int WEBSITECV = 112;
        public const int PRODUCTIMAGEFORESHOP = 113;
        public const int COLOR = 114;
        public const int OUTLET = 115;
        public const int ESHOPMEMBERSHIP = 116;
        public const int PRODUCTDESCRIPTION = 117;
        public const int PRODUCTATTENTION = 118;
        public const int FISHERIESUNIT = 119;
        public const int FISHERIESPRODUCTTYPE = 120;
        public const int POND = 121;
        public const int FISHERIESINVENTORY = 122;
        public const int FISHERIESINVENTORYOUT = 123;
        public const int SHOPINVENTORY = 124;
        public const int DAILYCOSTVAUCHERREASON = 125;
        public const int DAILYMISCELLANEOUSCOST = 126;



    }
}
