export interface ShopGoodSale {    
    shopGoodSaleId: number,
    warehouseId: number,
    supplierId:number,
    paymentStatusId:number,
    voucherNo: string,
    saleDate: string,
    totalSalePrice: string,
    saleLessAmount: string,
    grandTotalSalePrice: string,
    customerPaidAmount: string,
    customerDueAmount: string,
    remarks:string,
    approveStatus:number,
    shopGoodSaleDetailId:number,
    fisheriesProductTypeId:number,
    fisheriesUnitId:number,
    saleQty:string,
    salePrice: string,
    rowTotalSalePrice: string,
    costingPrice:string,
    unitPurchasePrice:string,
    profit:string,
    isActive: boolean
}
