export interface Supplier {
    supplierId: number,
    customerTypeId:number,
    supplierTypeId:number,
    divisionId: number,
    districtId: number,
    districName: string,
    upazilaName: string,
    upazilaId: number,
    categoryId: number,
    productTypeId: number,
    warehouseId:number,
    supplierName: string,
    shopName: string,
    address: string,
    countryId:number,
    tin: string,
    tradeLicenseNo: string,
    phoneNo: string,
    email: string,
    contactPerson: string,
    supplierStatus: number,
    commissionPercent:number,
    commissionPaidDate:string,
    creditLimitAmount:number,
    monthClosingDate:string,
    clientsImage:string,
    remarks: string,
    totalAdvanceAmount:number,
    totalDueAmount:number,
    totalPaidAmount:number,
    customerTypeName:string,
    warehouse:string,
    isActive: boolean
}